### ISSUE TITLE
the rq module does not contain functions which solve "EXACT (r,Q) PROBLEM WITH CONTINUOUS DEMAND DISTRIBUTION" ,why?

### ISSUE THREAD

**Issue by A-Pai** [LarrySnyder/stockpyl#122]
the rq module does not contain functions which solve "EXACT (r,Q) PROBLEM WITH CONTINUOUS DEMAND DISTRIBUTION" ,why?

**Comment by LarrySnyder** [comment]
I have not implemented this algorithm yet, but I intend to; see issue #34.

**Comment by A-Pai** [comment]
您的邮件我已收到  I have received your email                        李刚  Li Gang
