### ISSUE TITLE
Correctly invoke `s_s_cost_discrete` with updated arguments

### ISSUE THREAD

**Issue by finnwiz** [LarrySnyder/stockpyl#132]
Within `ss.py`, Lines 289-294:

```	# Initialize incumbent and cost.
	S_hat = S0
	s_hat = s0
	g_hat = s_s_cost_discrete(s_hat, S_hat, holding_cost, stockout_cost,
							  fixed_cost, use_poisson, demand_mean,
							  demand_pmf_dict)
```

I think the signature of `s_s_cost_discrete` is:

```
def s_s_cost_discrete(reorder_point, order_up_to_level, holding_cost,
					  stockout_cost, fixed_cost, use_poisson, demand_mean=None,
					  demand_hi=None, demand_pmf=None):
```

I'd suggest we invoke the function in `ss.py` on line 292 to:
```
	g_hat = s_s_cost_discrete(s_hat, S_hat, holding_cost, stockout_cost,
							  fixed_cost, use_poisson, demand_mean,
							  demand_hi, demand_pmf)
```

This was giving me errors when computing (s,S) levels for custom discrete distributions.

I'd be happy to make a PR but am a little confused on the permissions.

**Comment by LarrySnyder** [comment]
@finnwiz Thanks for this and sorry it took me a couple weeks to notice it.

You're correct. I'll make the change. 

I think there are a few other errors in that function, actually, which your issue made me notice. In particular in 281 

```
		gsS0 = s_s_cost_discrete(s, S0, holding_cost, stockout_cost, fixed_cost,
							 use_poisson, demand_mean, demand_hi, demand_pmf)
```
I think `demand_pmf` should be `demand_pmf_dict`, and a few other places as well.

**Comment by LarrySnyder** [comment]
Also for future reference, feel free to just make the PR and I'll figure it out from there.

**Comment by finnwiz** [comment]
Okay great. Will make a PR in the future. Thank you!
