### ISSUE TITLE
Add OWMR-creation function to `supply_chain_network.py`

### ISSUE THREAD

**Issue by LarrySnyder** [LarrySnyder/stockpyl#56]

**Comment by WhiteByeBye** [comment]
Hi, Dr. Snyder

I read the textbook entitled "Foundation of Inventory Management", by Dr. Zipkin, and it says 
>OWMR (aka. distribution systems) with FIFO rule and local base stock level can be optimized easily (page 334)

And I found stockpyl, such a powerful tool. Thanks for your great work! 

Kindly asking if there any method to optimize OWMR system (e.g., get the vector of $S^\prime_j$) in stockpyl?

**Comment by LarrySnyder** [comment]
@WhiteByeBye The short answer is no, unfortunately I haven't implemented any optimization methods for distribution systems yet. (If you have any interest in working on this, let me know!)

But I don't see the sentence that you quoted in Zipkin's book. Maybe we have different editions? In general OWMR and other distribution systems are hard, so I'm surprised to see a quote saying it's easy, even for FIFO + base-stock policy. For example, on p. 334 of my edition, he says "Unfortunately, there is no simple, elegant procedure to optimize this function," referring to the OWMR expected cost function.

**Comment by WhiteByeBye** [comment]
Hi Dr. @LarrySnyder 

Thanks for your reply! I appreciate the insight. I must apologize for the confusion in my previous message—the quote was my interpretation and not a direct citation from Zipkin’s book. 

Regarding the book, after the statement, 
> "Unfortunately, there is no simple, elegant procedure to optimize this function," 

Zipkin indeed discusses a projection method, stating: 
> "The most popular approach is a projection method: ... The advantage of this approach is that, with $s_0^{\prime}$ temporarily fixed, the objective function $C\left(s_0^{\prime}, \mathbf{s}^{\prime}\right)$ separates by $j$, so the inner loop can optimize over each $s_j^{\prime}$ separately." 

He then uses the normal distribution to approximate the remainder of the discussion.

It seems I misunderstood the depth of the discussion in the text. And I acknowledge that inventory/supply-chain management may not be my primary research focus in the foreseeable future, and at this very moment, I may not have the adequate skills to contribute effectively to stockpyl. However, if I find myself able to contribute at any point, I will definitely reach out.
