### ISSUE TITLE
Are you sure you need such a recent pandas?

### ISSUE THREAD

**Issue by pjcpjc** [LarrySnyder/stockpyl#84]
```
 stockpyl 0.0.8 depends on pandas>=1.4.2
```

Are you **sure** you need this recent a `pandas`?  `pandas` generally does a great job with backwards compatibility, and thus if it works with a slightly older `pandas`, it will (almost always) with the newest `pandas`. It is thus a kindness to keep your dependency requirement a bit older, assuming you can do so without breaking anything.

This is where Anaconda virtual environments and unittests are your friend. Make a quickie environment with an older version of `pandas`, run the unit tests on `stockpyxl` there, and if they work, then you can relax the `pandas` that is forced with the install. 

Just a suggestion, feel free to kill if you don't want to look into this.

**Comment by LarrySnyder** [comment]
@pjcpjc Ha. Actually it turns out the package doesn't even use pandas anymore. So I removed the dependency. Thanks for the suggestion.

**Comment by pjcpjc** [comment]
You the man!
