### ISSUE TITLE
load_instance doesn't work with default arguments

### ISSUE THREAD

**Issue by pjcpjc** [LarrySnyder/stockpyl#85]
```
from stockpyl.instances import load_instance
tree = load_instance("example_6_5")
```

This doesn't work unless the `stockpyl_instances.json` file is at `/Users/datasets/stockpyl_instances.json` (at least on my machine). I studied the repo and got it working easily enough, but since `stockpyl_instances.json` is small you could just do what scikit-learn does and install it with the package itself, and thus have `load_instance`, by default, locate the file that was installed when the package is installed.

I've done this before this way.

**Step one**

`package_data={'my_package': ["*.json"]}`

as an entry in the `setuptools.setup` call in the `setup.py` file. (I assume something analogous works`setup.cfg` ... it might be a little trickier here for you since you are using a `src` directory and I am using [this](https://docs.python-guide.org/writing/structure/) format).

**Step two**

`stockpyl_instances.json` now lives in your package directory. (Same directory as the .py file that has `def load_instance`)

**Step three**

```
def _stockpyl_instances_json_path():
    code_file = os.path.abspath(inspect.getsourcefile(_stockpyl_instances_json_path))
    rtn = os.path.join(os.path.dirname(code_file), "stockpyl_instances.json")
    assert os.path.exists(rtn) and os.path.isfile(rtn)
    return rtn
```

in the `def load_instance` file, and then modify `load_instance` to call `_stockpyl_instances_json_path` when the `filepath` argument is at the default value (which would now be None).

I tested it by creating the whl file manually and then pip installing that locally and then playing around with it before pip uninstalling it.

**Comment by LarrySnyder** [comment]
@pjcpjc Thanks for catching this. The way files get handled in a package has definitely confused me. I will try the approach you suggested. Two questions:
1. `package_data={'my_package': ["*.json"]}` -- `'my_package'` becomes `'stockpyl'`, right?
2. I'd rather put a `datasets` directory in `src/stockpyl/` and put the json in there, instead of putting the json directly in `src/stockpyl/`. Then I would just adjust the path in `_stockpyl_instances_json_path()` accordingly -- right?

**Comment by LarrySnyder** [comment]
@pjcpjc I think I've got it working, but would you mind taking a look and testing it?

My changes are in the `dataset_loc` branch (https://github.com/LarrySnyder/stockpyl/tree/dataset_loc).

If you give me the 👍 I'll merge the branches and deploy a new release.

**Comment by pjcpjc** [comment]
@LarrySnyder can you just make a .whl? I think `python setup.py sdist bdist_wheel` will do it, but since I don't use `setup.cfg` I'm not 100% sure. If you make a .whl file I'll play with it.

**Comment by LarrySnyder** [comment]
@pjcpjc Try this. Not sure if I successfully built this whl from the correct branch, so if it doesn't work, let me know and I'll try a different way.

https://github.com/LarrySnyder/stockpyl/blob/dataset_loc/stockpyl-0.0.8-py3-none-any.whl?raw=true

**Comment by pjcpjc** [comment]
```
In [1]: from stockpyl.instances import load_instance

In [2]: tree = load_instance("example_6_5")
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 tree = load_instance("example_6_5")

File ~/anaconda3/envs/larrysnyder/lib/python3.10/site-packages/stockpyl/instances.py:87, in load_instance(instance_name, filepath, initialize_missing_attributes, ignore_state_vars)
     85 # Determine filepath.
     86 if filepath is None:
---> 87 	filepath = _stockpyl_instances_json_path()
     89 # Does JSON file exist?
     90 if os.path.exists(filepath):
     91 	# Use this path.

File ~/anaconda3/envs/larrysnyder/lib/python3.10/site-packages/stockpyl/instances.py:291, in _stockpyl_instances_json_path()
    289 code_file = os.path.abspath(inspect.getsourcefile(_stockpyl_instances_json_path))
    290 rtn = os.path.join(os.path.dirname(code_file), "datasets/stockpyl_instances.json")
--> 291 assert os.path.exists(rtn) and os.path.isfile(rtn)
    292 return rtn

AssertionError: 
```

**Comment by pjcpjc** [comment]
Also, don't do this
```
rtn = os.path.join(os.path.dirname(code_file), "datasets/stockpyl_instances.json")
```
under any circumstances. since the second argument is correct only on some OS's and not others. Do this instead

```
rtn = os.path.join(os.path.dirname(code_file), "datasets", "stockpyl_instances.json")
```

**Comment by LarrySnyder** [comment]
@pjcpjc OK, try again: https://github.com/LarrySnyder/stockpyl/blob/master/stockpyl-0.0.8-py3-none-any.whl?raw=true

**Comment by pjcpjc** [comment]
🔥 
Works!

**Comment by LarrySnyder** [comment]
@pjcpjc Awesome, thanks!
